services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      # - "MYSQL_DATABASE=ecomdb"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=david"
      - "MYSQL_PASSWORD=123"
    # volumes:
    #   - /Backup:/var/lib/mysql
    networks:
      - pythonapp

  app:
    build: .
    ports:
      - "5007:5007"
      # - "8000:8000"
      # - "80:80"
    networks:
      - pythonapp
    restart: always
    depends_on:
      - mysql

networks:
  pythonapp:


# cat Dump.sql | docker exec -i mysql /usr/bin/mysql -u root --password=9317 online_store